=== Dr-Omega/felt-craft-lab/benchmarks/fabrication-layer-decomposition/vector-edge-smoothing/schemas/vectorization_result.schema.json
{
  "$schema": "https://json-schema.org/draft/2020-12/schema",
  "type": "object",
  "required": ["schemaVersion", "caseId", "profile", "route", "inputSha256", "geometry", "metrics", "hardGate"],
  "additionalProperties": false,
  "properties": {
    "schemaVersion": {"const": "1.0.0-poc"},
    "caseId": {"type": "string", "pattern": "^FLD-[0-9]{3}$"},
    "profile": {"type": "string"},
    "route": {"enum": ["V0_EXACT_PIXEL_BOUNDARY", "V1_SIMPLIFIED_POLYGON", "V2_SMOOTH_BEZIER"]},
    "tolerancePx": {"type": ["number", "null"]},
    "inputSha256": {"type": "string", "pattern": "^[0-9a-f]{64}$"},
    "geometry": {"type": "array"},
    "metrics": {"type": "object"},
    "hardGate": {"type": "object"}
  }
}

=== Dr-Omega/felt-craft-lab/benchmarks/fabrication-layer-decomposition/vector-edge-smoothing/outputs/cp-b-balanced_rc-a/FLD-002/V2/tol-1p0/result.json
{"caseId":"FLD-002","geometry":[{"edgeId":"E000001","fallback":"V2_SMOOTH_BEZIER_CONTINUOUS_DEVIATION_FAIL_CLOSED_LEVEL_1","segments":[{"p0":[8.0,604.0],"p1":[9.0,45.0],"type":"LINE"}]},{"edgeId":"E000002","fallback":null,"segments":[{"p0":[8.0,604.0],"p1":[8.0,656.0],"type":"LINE"},{"c1":[8.0,657.58004262],"c2":[7.24344992,661.0],"p0":[8.0,656.0],"p1":[9.0,661.0],"type":"CUBIC"}]},{"edgeId":"E000003","fallback":null,"segments":[{"c1":[9.75655008,604.0],"c2":[9.0,607.41995738],"p0":[8.0,604.0],"p1":[9.0,609.0],"type":"CUBIC"},{"p0":[9.0,609.0],"p1":[9.0,661.0],"type":"LINE"}]},{"edgeId":"E000004","fallback":null,"segments":[{"c1":[9.0,43.66666667],"c2":[8.66666667,44.0],"p0":[9.0,45.0],"p1":[10.0,44.0],"type":"CUBIC"}]},{"edgeId":"E000005","fallback":null,"segments":[{"c1":[10.33333333,45.0],"c2":[10.0,45.33333333],"p0":[9.0,45.0],"p1":[10.0,44.0],"type":"CUBIC"}]},{"edgeId":"E000006","fallback":null,"segments":[{"p0":[9.0,661.0],"p1":[9.0,683.0],"type":"LINE"},{"c1":[9.93006333,683.0],"c2":[11.0,694.20918685],"p0":[9.0,683.0],"p1":[11.0,696.0],"type":"CUBIC"},{"c1":[11.85490713,696.0],"c2":[14.0,702.22860123],"p0":[11.0,696.0],"p1":[14.0,704.0],"type":"CUBIC"},{"c1":[14.9565647,704.0],"c2":[19.0,709.14670777],"p0":[14.0,704.0],"p1":[19.0,710.0],"type":"CUBIC"}]},{"edgeId":"E000007","fallback":null,"segments":[{"c1":[10.0,41.66666667],"c2":[9.43333333,41.0],"p0":[10.0,43.0],"p1":[11.0,41.0],"type":"CUBIC"}]},{"edgeId":"E000008","fallback":null,"segments":[{"p0":[10.0,43.0],"p1":[10.0,44.0],"type":"LINE"}]},{"edgeId":"E000009","fallback":null,"segments":[{"c1":[11.56666667,43.0],"c2":[11.0,42.33333333],"p0":[10.0,43.0],"p1":[11.0,41.0],"type":"CUBIC"}]},{"edgeId":"E000010","fallback":null,"segments":[{"c1":[11.0,39.66666667],"c2":[10.43333333,39.0],"p0":[11.0,41.0],"p1":[12.0,39.0],"type":"CUBIC"}]},{"edgeId":"E000011","fallback":null,"segments":[{"c1":[12.56666667,41.0],"c2":[12.0,40.33333333],"p0":[11.0,41.0],"p1":[12.0,39.0],"type":"CUBIC"}]},{"edgeId":"E000012","fallback":null,"segments":[{"c1":[12.0,37.66666667],"c2":[11.43333333,37.0],"p0":[12.0,39.0],"p1":[13.0,37.0],"type":"CUBIC"}]},{"edgeId":"E000013","fallback":null,"segments":[{"c1":[13.56666667,39.0],"c2":[13.0,38.33333333],"p0":[12.0,39.0],"p1":[13.0,37.0],"type":"CUBIC"}]},{"edgeId":"E000014","fallback":null,"segments":[{"c1":[13.0,34.66666667],"c2":[12.66666667,35.0],"p0":[13.0,36.0],"p1":[14.0,35.0],"type":"CUBIC"}]},{"edgeId":"E000015","fallback":null,"segments":[{"p0":[13.0,36.0],"p1":[13.0,37.0],"type":"LINE"}]},{"edgeId":"E000016","fallback":null,"segments":[{"c1":[14.33333333,36.0],"c2":[14.0,36.33333333],"p0":[13.0,36.0],"p1":[14.0,35.0],"type":"CUBIC"}]},{"edgeId":"E000017","fallback":null,"segments":[{"c1":[14.0,33.66666667],"c2":[13.66666667,34.0],"p0":[14.0,35.0],"p1":[15.0,34.0],"type":"CUBIC"}]},{"edgeId":"E000018","fallback":null,"segments":[{"c1":[15.33333333,35.0],"c2":[15.0,35.33333333],"p0":[14.0,35.0],"p1":[15.0,34.0],"type":"CUBIC"}]},{"edgeId":"E000019","fallback":null,"segments":[{"c1":[15.0,32.66666667],"c2":[14.66666667,33.0],"p0":[15.0,34.0],"p1":[16.0,33.0],"type":"CUBIC"}]},{"edgeId":"E000020","fallback":null,"segments":[{"c1":[16.33333333,34.0],"c2":[16.0,34.33333333],"p0":[15.0,34.0],"p1":[16.0,33.0],"type":"CUBIC"}]},{"edgeId":"E000021","fallback":null,"segments":[{"c1":[16.0,31.66666667],"c2":[15.66666667,32.0],"p0":[16.0,33.0],"p1":[17.0,32.0],"type":"CUBIC"}]},{"edgeId":"E000022","fallback":null,"segments":[{"c1":[17.33333333,33.0],"c2":[17.0,33.33333333],"p0":[16.0,33.0],"p1":[17.0,32.0],"type":"CUBIC"}]},{"edgeId":"E000023","fallback":null,"segments":[{"c1":[17.0,30.66666667],"c2":[16.66666667,31.0],"p0":[17.0,32.0],"p1":[18.0,31.0],"type":"CUBIC"}]},{"edgeId":"E000024","fallback":null,"segments":[{"c1":[18.0,29.66666667],"c2":[17.66666667,30.0],"p0":[18.0,31.0],"p1":[19.0,30.0],"type":"CUBIC"}]},{"edgeId":"E000025","fallback":null,"segments":[{"c1":[19.33333333,31.0],"c2":[19.0,31.33333333],"p0":[18.0,31.0],"p1":[19.0,30.0],"type":"CUBIC"}]},{"edgeId":"E000026","fallback":null,"segments":[{"p0":[19.0,30.0],"p1":[20.0,30.0],"type":"LINE"}]},{"edgeId":"E000027","fallback":null,"segments":[{"c1":[19.0,711.33333333],"c2":[18.66666667,711.0],"p0":[19.0,710.0],"p1":[20.0,711.0],"type":"CUBIC"}]},{"edgeId":"E000028","fallback":null,"segments":[{"c1":[20.33333333,710.0],"c2":[20.0,709.66666667],"p0":[19.0,710.0],"p1":[20.0,711.0],"type":"CUBIC"}]},{"edgeId":"E000029","fallback":null,"segments":[{"c1":[20.0,28.66666667],"c2":[19.66666667,29.0],"p0":[20.0,30.0],"p1":[21.0,29.0],"type":"CUBIC"}]},{"edgeId":"E000030","fallback":null,"segments":[{"c1":[21.33333333,30.0],"c2":[21.0,30.33333333],"p0":[20.0,30.0],"p1":[21.0,29.0],"type":"CUBIC"}]},{"edgeId":"E000031","fallback":null,"segments":[{"c1":[20.0,712.33333333],"c2":[19.66666667,712.0],"p0":[20.0,711.0],"p1":[21.0,712.0],"type":"CUBIC"}]},{"edgeId":"E000032","fallback":null,"segments":[{"c1":[21.33333333,711.0],"c2":[21.0,710.66666667],"p0":[20.0,711.0],"p1":[21.0,712.0],"type":"CUBIC"}]},{"edgeId":"E000033","fallback":null,"segments":[{"c1":[21.0,27.66666667],"c2":[20.66666667,28.0],"p0":[21.0,29.0],"p1":[22.0,28.0],"type":"CUBIC"}]},{"edgeId":"E000034","fallback":null,"segments":[{"c1":[22.33333333,29.0],"c2":[22.0,29.33333333],"p0":[21.0,29.0],"p1":[22.0,28.0],"type":"CUBIC"}]},{"edgeId":"E000035","fallback":null,"segments":[{"c1":[21.0,713.33333333],"c2":[20.66666667,713.0],"p0":[21.0,712.0],"p1":[22.0,713.0],"type":"CUBIC"}]},{"edgeId":"E000036","fallback":null,"segments":[{"c1":[22.33333333,712.0],"c2":[22.0,711.66666667],"p0":[21.0,712.0],"p1":[22.0,713.0],"type":"CUBIC"}]},{"edgeId":"E000037","fallback":null,"segments":[{"p0":[22.0,28.0],"p1":[23.0,28.0],"type":"LINE"}]},{"edgeId":"E000038","fallback":null,"segments":[{"c1":[22.0,714.33333333],"c2":[21.66666667,714.0],"p0":[22.0,713.0],"p1":[23.0,714.0],"type":"CUBIC"}]},{"edgeId":"E000039","fallback":null,"segments":[{"c1":[23.33333333,713.0],"c2":[23.0,712.66666667],"p0":[22.0,713.0],"p1":[23.0,714.0],"type":"CUBIC"}]},{"edgeId":"E000040","fallback":null,"segments":[{"c1":[23.0,26.03033722],"c2":[24.90196816,26.0],"p0":[23.0,28.0],"p1":[27.0,26.0],"type":"CUBIC"}]},{"edgeId":"E000041","fallback":null,"segments":[{"c1":[24.36692992,28.0],"c2":[27.0,27.23856086],"p0":[23.0,28.0],"p1":[27.0,26.0],"type":"CUBIC"}]},{"edgeId":"E000042","fallback":null,"segments":[{"c1":[23.0,715.33333333],"c2":[22.66666667,715.0],"p0":[23.0,714.0],"p1":[24.0,715.0],"type":"CUBIC"}]},{"edgeId":"E000043","fallback":null,"segments":[{"c1":[24.33333333,714.0],"c2":[24.0,713.66666667],"p0":[23.0,714.0],"p1":[24.0,715.0],"type":"CUBIC"}]},{"edgeId":"E000044","fallback":null,"segments":[{"c1":[24.0,716.33333333],"c2":[23.66666667,716.0],"p0":[24.0,715.0],"p1":[25.0,716.0],"type":"CUBIC"}]},{"edgeId":"E000045","fallback":null,"segments":[{"c1":[25.33333333,715.0],"c2":[25.0,714.66666667],"p0":[24.0,715.0],"p1":[25.0,716.0],"type":"CUBIC"}]},{"edgeId":"E000046","fallback":null,"segments":[{"c1":[25.0,717.56666667],"c2":[25.66666667,717.0],"p0":[25.0,716.0],"p1":[27.0,717.0],"type":"CUBIC"}]},{"edgeId":"E000047","fallback":null,"segments":[{"c1":[26.33333333,716.0],"c2":[27.0,715.43333333],"p0":[25.0,716.0],"p1":[27.0,717.0],"type":"CUBIC"}]},{"edgeId":"E000048","fallback":null,"segments":[{"c1":[27.0,24.43333333],"c2":[27.66666667,25.0],"p0":[27.0,26.0],"p1":[29.0,25.0],"type":"CUBIC"}]},{"edgeId":"E000049","fallback":null,"segments":[{"c1":[28.33333333,26.0],"c2":[29.0,26.56666667],"p0":[27.0,26.0],"p1":[29.0,25.0],"type":"CUBIC"}]},{"edgeId":"E000050","fallback":"V2_SMOOTH_BEZIER_CONTINUOUS_DEVIATION_FAIL_CLOSED_LEVEL_1","segments":[{"p0":[27.0,48.0],"p1":[27.0,54.0],"type":"LINE"},{"p0":[27.0,54.0],"p1":[30.0,61.0],"type":"LINE"},{"p0":[30.0,61.0],"p1":[30.0,70.0],"type":"LINE"},{"p0":[30.0,70.0],"p1":[33.0,74.0],"type":"LINE"},{"p0":[33.0,74.0],"p1":[33.0,83.0],"type":"LINE"},{"p0":[33.0,83.0],"p1":[37.0,91.0],"type":"LINE"},{"p0":[37.0,91.0],"p1":[38.0,101.0],"type":"LINE"},{"p0":[38.0,101.0],"p1":[40.0,102.0],"type":"LINE"},{"p0":[40.0,102.0],"p1":[41.0,108.0],"type":"LINE"},{"p0":[41.0,108.0],"p1":[43.0,110.0],"type":"LINE"},{"p0":[43.0,110.0],"p1":[44.0,117.0],"type":"LINE"},{"p0":[44.0,117.0],"p1":[47.0,121.0],"type":"LINE"},{"p0":[47.0,121.0],"p1":[50.0,130.0],"type":"LINE"},{"p0":[50.0,130.0],"p1":[52.0,131.0],"type":"LINE"},{"p0":[52.0,131.0],"p1":[52.0,134.0],"type":"LINE"},{"p0":[52.0,134.0],"p1":[54.0,134.0],"type":"LINE"},{"p0":[54.0,134.0],"p1":[57.0,143.0],"type":"LINE"},{"p0":[57.0,143.0],"p1":[60.0,145.0],"type":"LINE"},{"p0":[60.0,145.0],"p1":[61.0,149.0],"type":"LINE"},{"p0":[61.0,149.0],"p1":[66.0,154.0],"type":"LINE"},{"p0":[66.0,154.0],"p1":[67.0,158.0],"type":"LINE"},{"p0":[67.0,158.0],"p1":[76.0,168.0],"type":"LINE"},{"p0":[76.0,168.0],"p1":[76.0,170.0],"type":"LINE"},{"p0":[76.0,170.0],"p1":[100.0,195.0],"type":"LINE"},{"p0":[100.0,195.0],"p1":[102.0,195.0],"type":"LINE"},{"p0":[102.0,195.0],"p1":[113.0,206.0],"type":"LINE"},{"p0":[113.0,206.0],"p1":[115.0,206.0],"type":"LINE"},{"p0":[115.0,206.0],"p1":[119.0,210.0],"type":"LINE"},{"p0":[119.0,210.0],"p1":[122.0,210.0],"type":"LINE"},{"p0":[122.0,210.0],"p1":[123.0,211.0],"type":"LINE"},{"p0":[123.0,211.0],"p1":[123.0,213.0],"type":"LINE"},{"p0":[123.0,213.0],"p1":[124.0,214.0],"type":"LINE"},{"p0":[124.0,214.0],"p1":[134.0,219.0],"type":"LINE"},{"p0":[134.0,219.0],"p1":[136.0,222.0],"type":"LINE"},{"p0":[136.0,222.0],"p1":[142.0,224.0],"type":"LINE"},{"p0":[142.0,224.0],"p1":[143.0,226.0],"type":"LINE"},{"p0":[143.0,226.0],"p1":[149.0,228.0],"type":"LINE"},{"p0":[149.0,228.0],"p1":[150.0,230.0],"type":"LINE"},{"p0":[150.0,230.0],"p1":[153.0,230.0],"type":"LINE"},{"p0":[153.0,230.0],"p1":[161.0,234.0],"type":"LINE"},{"p0":[161.0,234.0],"p1":[162.0,236.0],"type":"LINE"},{"p0":[162.0,236.0],"p1":[173.0,239.0],"type":"LINE"},{"p0":[173.0,239.0],"p1":[176.0,242.0],"type":"LINE"},{"p0":[176.0,242.0],"p1":[182.0,243.0],"type":"LINE"},{"p0":[182.0,243.0],"p1":[187.0
